### ISSUE TITLE
Error for running simulation examples

### ISSUE THREAD

**Issue by faridafrh** [icarus-sim/icarus#10]
Hello, I'm working on my master thesis and i'm going to try a new caching strategy with icarus, as to begin i try to run the examples but it's giving me the error that icarus is not installed, although it has been installed. i really appreciate if you can help me.
![screenshot from 2019-02-11 04-28-32](https://user-images.githubusercontent.com/47525832/52563199-f6201780-2e15-11e9-848f-dfa13cde7340.png)

**Comment by lorenzosaino** [comment]
@faridafrh: thanks for reporting it. This is now fixed in master.
