### ISSUE TITLE
accessing link load

### ISSUE THREAD

**Issue by faridafrh** [icarus-sim/icarus#12]
Hello,
i'm trying to write a new strategy for caching and i need link load for my computation, i'm a little confused, can you help me how to use it in on path class? i don't know if i can use the collectors class or not? :(
i really appreciate it if you could give me a hint
thanks

**Comment by lorenzosaino** [comment]
Hello,

When you implement your own strategy you don't need to do anything specifically to measure the link load. When implementing a strategy you will use methods from the `NetworkController` class like `forward_request_path`, `forward_content_path`, `get_content`, `put_content` etc... These methods under the hood invoke all collectors to collect desires metrics.

All you have to do is to ensure that in the configuration file you have a `DATA_COLLECTORS` variable that's a list and includes `LINK_LOAD`, like this: https://github.com/icarus-sim/icarus/blob/895b1658dfdc175254173bf510d4f31056227166/config.py#L230-L235. That's all. If you do that, running experiments with your own strategy will automatically collect link load measurements.

**Comment by faridafrh** [comment]
yes you're right i know these. but i want to use link load as a parameter to decide about the caching place.
actually i'm working on my thesis for this idea and i want to use link loads as a weight of edges and use shortest path for a weighted graph to reduce load, i don't if this would work but i'm really stock on how to use link loads or even delay as a weight pf edges  to make a little improvement on either load of the network or the latency.

**Comment by faridafrh** [comment]
yes you're right i know these. but i want to use link load as a parameter to decide about the caching place.
actually i'm working on my thesis for this idea and i want to use link loads as a weight of edges and use shortest path for a weighted graph to reduce load, i don't if this would work but i'm really stock on how to use link loads or even delay as a weight of edges to make a little improvement on either load of the network or the latency.

**Comment by lorenzosaino** [comment]
OK, thanks for the clarification. What you plan to do should be feasible with reasonably small changes. I will tell you how I would personally implement but there are a number of different approaches you could take.

I would implement everything within the class implementing your strategy. I would create a dictionary having as key the link (as a <origin, destination> tuple) and as a value an object that computes the link load for that link.

I would implement that object with two methods: one to store when a content was sent on a link at a given timestamp and another one to return the average link load over a given time window.

Whenever you forward a content on a link, I would invoke the method of that object to store that an object was transmitted and whenever you need to make link-load based decisions, I would invoke the other method to get the link load.

With this approach your strategy will have visibility into the link load of each link.

If you want to periodically change the routing table entirely based on link load, you can do that too. The way I would go about it is to add a new method to the `NetworkController` class that allows you to replace the routing table (or recompute the routing table based on link load) and that method internally updates or replaces `self.model.shortest_path`, which stores the routing table.

Hope this helps. Good luck with your work!

**Comment by faridafrh** [comment]
Thank you so much for your help. Yes, you're right. I have also thought of different approaches, But as I'm new to python and I just started learning it with Icarus, I am a little confused. The problem for me is how to calculate link load in strategy class cause in calculating link load in DataCollector module NetworkController notifies the collector proxy of the events happening, and that's the part that I get confused,  I don't know how to get my needed data for calculating the link load in strategy class.  
I really don't know how to thank you for answering my questions cause I have a little time for finishing this project and there's is absolutely no one in our university who have worked on this matter.
Thank you so much.

**Comment by lorenzosaino** [comment]
I am very glad to hear my answers were helpful. I am going to close this issue for now. Feel free to reopen it if you have any further questions about this. Best of luck with your project!

**Comment by faridafrh** [comment]
Hi, @lorenzosaino I'm very sorry for my endless questions.
About the part " store when a content was sent on a link at a given timestamp" you mean that in that method I should store the timestamp of content transmission or I should just have the count of transmissions?
to be more precise for each link I should have a list of timestamps that contents are transmitted in that timestamp or only the number of transmissions?

**Comment by lorenzosaino** [comment]
The link load is a metric that's computed over a time period. I assume that when you want to make decisions based on link load you will want to look at the value over the last 10s or last minute and so on.

If you don't store the timestamp you will not be able to compute the link load over a given period of time. You may only store the counter without timestamp, but then you will only be able to compute the link load since the start of the simulation, which I imagine is not what you want.

Does this answer your question?

**Comment by faridafrh** [comment]
yes, exactly.
I'm working on it.
By the way, I have another question. after calculating link load I want to set it as the weight of each link so that I can change the node betweenness centrality according to that. but I assume I cannot set the weight of topology links in strategy class. should I add some functions to the network module?

**Comment by lorenzosaino** [comment]
> I'm working on it. but I don't know if I should just consider contents or both requests and contents?

For accuracy, I think you should consider both but since contents are considerably larger than requests, if you only consider contents results should not change much.

> after calculating link load I want to set it as the weight of each link so that I can change the node betweenness centrality according to that. but I assume I cannot set the weight of topology links in strategy class. should I add some functions to the network module?

That's correct. You cannot change the topology in the strategy. The routing table (i.e., all the shortest paths) is stored in the `shortest_path` instance variable of the `NetworkModel` class, but you cannot access `NetworkModel` directly from the `Strategy`. You need to do it via the `NetworkController`. The way I would go about it is to add a new method to the `NetworkController` class that allows you to replace the routing table (or recompute the routing table based on link load) and that method internally updates or replaces self.model.shortest_path, which stores the routing table.

**Comment by faridafrh** [comment]
Actually I was not thinking of changing the routing table, my idea was to recalculate betweenness centrality of the nodes based on the link loads, I mean now betw is calculated by using shortest path with weight=1, I want to change it in a way that it uses weighted shortest path and the weight will be the link load. The rationale behind my idea was to lessen the load on the node with the highest betw. I'm not sure if this will work or not.
so for this purpose, I was going to add  a function to the controller that can set weight on topology links

**Comment by faridafrh** [comment]
Hello @lorenzosaino 
I have faced a situation that I don't know if it's right or not; I have done as I said in my strategy, the results I get somehow surprised me. Random choice strategy is performing better in cache hit ratio and latency than CL4M especially in WIDE topology, but in their paper, the results are far more better than Random choice. Do you know why it is like this?
I have attached one of the diagrams as an example.
![Screenshot from 2019-05-12 08-24-30](https://user-images.githubusercontent.com/47525832/57584382-df11c400-74ef-11e9-9c55-58f5e40d1b0a.png)

**Comment by lorenzosaino** [comment]
For some reason, I missed a notification regarding this last message. Anyway, I would have not been able to provide good advice cause on this issue.
