### ISSUE TITLE
Rocket_fuel_latency topology

### ISSUE THREAD

**Issue by faridafrh** [icarus-sim/icarus#13]
Hello @lorenzosaino 
I was trying to run CL4M with rocket_fuel_latency topology and I got an error in orchestration file, this line: 
"  topology = TOPOLOGY_FACTORY[topology_name](**topology_spec) " 
hope you can help me to resolve this. 
![Screenshot from 2019-04-22 09-06-26](https://user-images.githubusercontent.com/47525832/56510359-cfc9d700-653e-11e9-9f65-f424b60c1d5d.png)

**Comment by lorenzosaino** [comment]
The configuration file in that example does not include experiments using the RocketFuel topology. Did you change the configuration file?

**Comment by faridafrh** [comment]
Yes, I have changed the configuration file and added ROCKET_FUEL in topologies, but I don't know if I have to change another part because as I was searching, I found that I should give delay as an input parameter.

**Comment by lorenzosaino** [comment]
Thanks for the clarification. If you want me to help you debugging your issue you'll need to share your configuration or else I will not be able to reproduce your issue.

**Comment by faridafrh** [comment]
@lorenzosaino actually I haven't changed any configuration of the example, I just added rocket_fuel topology.
[config.zip](https://github.com/icarus-sim/icarus/files/3134000/config.zip)

**Comment by lorenzosaino** [comment]
Yes, but the topologies in the example don't require any additional parameter, the RocketFuel topologies do. You need at least to specify which ASN to use, as explained in https://github.com/icarus-sim/icarus/blob/master/config.py#L86-L91. Admittedly that piece of documentation is a bit hard to find, I should make that easier to find. 

Anyway, if you replace the nested of L117 with this this below, it should work:

```for alpha in ALPHA:
    for strategy in STRATEGIES:
        for topology in TOPOLOGIES:
            for network_cache in NETWORK_CACHE:
                if topology == "ROCKET_FUEL":
                    experiment['topology']['asn'] = 3257
                experiment = copy.deepcopy(default)
                experiment['workload']['alpha'] = alpha
                experiment['strategy']['name'] = strategy
                experiment['topology']['name'] = topology
                experiment['cache_placement']['network_cache'] = network_cache
                experiment['desc'] = "Alpha: %s, strategy: %s, topology: %s, network cache: %s" \
                                     % (str(alpha), strategy, topology, str(network_cache))
                EXPERIMENT_QUEUE.append(experiment)
```

Note that the only change added are these two lines below. This uses ASN 3257. You can use any ASN listed here: https://github.com/icarus-sim/icarus/tree/master/resources

```
                if topology == "ROCKET_FUEL":
                    experiment['topology']['asn'] = 3257
```

**Comment by faridafrh** [comment]
@lorenzosaino sorry for all the trouble, I didn't notice that file. you're right. I get it. but there is still an error that I  don't know what is causing it.
![Screenshot from 2019-05-03 01-08-20](https://user-images.githubusercontent.com/47525832/57125957-9b58e500-6da0-11e9-9c84-2d703f1a1384.png)

**Comment by lorenzosaino** [comment]
You're right, my snippet was incorrect. Try this one instead:

```
    for strategy in STRATEGIES:
        for topology in TOPOLOGIES:
            for network_cache in NETWORK_CACHE:
                experiment = copy.deepcopy(default)
                if topology == "ROCKET_FUEL":
                    experiment['topology']['asn'] = 3257
                experiment['workload']['alpha'] = alpha
                experiment['strategy']['name'] = strategy
                experiment['topology']['name'] = topology
                experiment['cache_placement']['network_cache'] = network_cache
                experiment['desc'] = "Alpha: %s, strategy: %s, topology: %s, network cache: %s" \
                                     % (str(alpha), strategy, topology, str(network_cache))
                EXPERIMENT_QUEUE.append(experiment)
```

**Comment by lorenzosaino** [comment]
I am going to close this issue. Please feel free to reopen if you have any further issues
