### ISSUE TITLE
Icarus plot

### ISSUE THREAD

**Issue by UmerBinSalman1** [icarus-sim/icarus#14]
Dr. Lorenzo

i am trying to plot the results from txt file in Icarus. I dont understand what will i do? please help me out.
i am very thankful.

**Comment by lorenzosaino** [comment]
Hi Umer,

Could you please provide more details? I need more information to be able to help you.

What txt file are you referring to? Icarus outputs results in a pickle file. How did you generate that file? And what are you interested in plotting specifically?
