### ISSUE TITLE
To make content-based replication

### ISSUE THREAD

**Issue by KimHeeSu1203** [icarus-sim/icarus#16]
Dr.Lorenzo

Thank you for providing me with great tools related to ICN.
I'm studying for caching algorithm in ICN especially content-based replication

In your paper, you mentioned that your ICN research are all cache-or node- based.
Is there any way to change it into content-based replication?

I'm sorry if it's an immature question because I'm not familiar with

thank you!

**Comment by lorenzosaino** [comment]
Hello,

I am glad to hear you find Icarus useful.

> In your paper, you mentioned that your ICN research are all cache-or node- based.
> Is there any way to change it into content-based replication?

I am not sure I understand the question correctly. What do you mean with "content-based replication". Do you mean replicating content across caches depending on characteristics of specific content items? If that's what you mean, yes, that's definitely possible, there are many proposals in literature that do that.

Did that answer your question?

Best regards,
Lorenzo

**Comment by KimHeeSu1203** [comment]
hi! 

thank you for kind answering
yes I mean contents caching depending on characteristics of content
I will try my best using your tool.

thank you
heesu Kim

**Comment by lorenzosaino** [comment]
Hi Heesu,

Just to clarify, Icarus doesn't have any of those policies implemented. All policies currently implemented are those listed in the paper. You can however implement any new policies you'd like to experiment on.

Best regards,
Lorenzo
