### ISSUE TITLE
Strategy extension

### ISSUE THREAD

**Issue by OliverZijia** [icarus-sim/icarus#18]
Hi,

Sorry for bothering you, this is my second question, I'd like to do an experiment for RL-based caching strategy, so I need to modify write a new class for the new RL-based strategy, do I need to run "make install" again when I add the new class to "policies.py"?

Or could you give me some instructions on how to modify it if there is a simpler method?

Good day, sir!

**Comment by lorenzosaino** [comment]
Hello,

No, `make install` installs Icarus in "editable" mode (that's the `-e` option in https://github.com/icarus-sim/icarus/blob/master/Makefile#L21). That means that when you change the code in Icarus, you don't need to reinstall it, it works automatically with the updated change.

I am closing this issue, feel free to reopen it if you have further questions.

Best regards,
Lorenzo
