### ISSUE TITLE
How to read 

### ISSUE THREAD

**Issue by adarboe** [icarus-sim/icarus#2]
Dr. Lorenzo

thank so much for reply on the ICN Mailing-list. Anyway I have tried your instructions and this is what I get:
abdou@sdn-ccn:~/icarus$ python scripts/printresults.py results.pickle > results.txt
Traceback (most recent call last):
  File "scripts/printresults.py", line 8, in <module>
    from icarus.registry import RESULTS_READER
ImportError: No module named icarus.registry

See if you can still help, thank you and sorry for bothering you.

Abdou Darboe
Wireless Internet Service Engineering Lab
NDHU, Hualien.
Taiwan, ROC

**Comment by lorenzosaino** [comment]
Hi Abdou,

I need more information to find the issue.

What Python version are you using? Is it 2.7? Have you installed all the required dependencies, i.e. fnss, networkx etc..?
What Icarus version are you using? 0.4.0? A different one? Or have you pulled the latest version of the source code from the repository? Also, did the simulations work fine to you?

I just tried with the latest version on the GitHub repo and it works fine to me.

**Comment by adarboe** [comment]
Hello and good day Dr. Saino,

Once again thanks so much for your helps I really appreciate. Actually I am using ubuntu 10.04 LTS, in which I installed Icarus-0.4.0, Python V 2.7 and also installed Python-3.4.3, FNSS version >=0.6.0,
Networkx version 1.6, Numpy version 1.4, Mako version 0.4.

Yes the simulation runs for me each time change the configuration file to my desire simulation parameters, I just can't interprete the reults, that's my main concern at the moment.

Thank you

**Comment by adarboe** [comment]
I mean Ubuntu 14.04 LTS, that was a typo.

Sorry

**Comment by lorenzosaino** [comment]
Hi Abdou,

I think I found the issue. Try adding the Icarus path to the PYTHONPATH variable. Do the following:
 * Move the main Icarus directory, i.e. the one containing the `README.md` and `LICENSE.txt` files.
 * Run the following command

````
    export PYTHONPATH=`pwd`:$PYTHONPATH
````

Then try printing the results again. Please let me know if this works for you so I can close this issue.

**Comment by adarboe** [comment]
Thanks so much Dr. Saino, you are truly a genius, how I wish I can have your intelligence hahahaha.... the problem is solved after following your instructions. Now I can have readable results of my simulation. I really appreciate your tireless efforts in helping me solve this issue. Have pleasant time out there.

Thank you again.
  


     On Saturday, 28 March 2015, 1:13, Lorenzo Saino <notifications@github.com> wrote:
   

 Hi Abdou,I think I found the issue. Try adding the Icarus path to the PYTHONPATH variable. Do the following:   
   - Move the main Icarus directory, i.e. the one containing the README.md and LICENSE.txt files.
   - Run the following command
    export PYTHONPATH=`pwd`:$PYTHONPATH
Then try printing the results again. Please let me know if this works for you so I can close this issue.—

**Comment by lorenzosaino** [comment]
Hi Abdou,

No need to thank me, I'm happy this solved your problem. I will improve Icarus documentation to make sure other people don't get the same problem again.

One last thing, please notice that setting the `PYTHONPATH` variable will not persist after you reboot your machine. To make it persistent you should add that command to, for example, the `.bashrc` file (if you use the Bash shell) or any other script that Ubuntu executes when it's booted.

Best regards and good luck with your research.
Lorenzo

**Comment by adarboe** [comment]
That's noted thanks so much.
