### ISSUE TITLE
Problems with cacheplacement scenario (DEGREE and BETWEENNESS_CENTRALITY methods)

### ISSUE THREAD

**Issue by AlecHang** [icarus-sim/icarus#21]
Hello Sir,

Firstly, a thousand thanks for providing this powerful tool for cache simulation. But during use, we found possible problems in the cache placement scenario (DEGREE and BETWEENNESS_CENTRALITY methods).

In DEGREE, the source code calculates and sums the degree of all nodes, however, only nodes from 'icr_candidates' are allocated cache budget. This will result in the cache budget not being fully allocated. Same thing in BETWEENNESS_CENTRALITY.

Some topologies got the wrong allocating result (like TISCALI and GEANT), some are right (like GARR).

Am I misunderstanding something? Looking forward to your response.

**Comment by lorenzosaino** [comment]
Hi Alec, 

Thanks for reporting this issue. Let me look into it and get back to you.

Best regards,
Lorenzo

**Comment by lorenzosaino** [comment]
Hi Alec,

I looked into it and it was in fact a bug. I pushed a commit that fixes the issue. Thanks again for reporting it.

Best regards,
Lorenzo
