### ISSUE TITLE
How to generate a dataset for content popularity and run simulations with our own algorithm

### ISSUE THREAD

**Issue by madhucharan** [icarus-sim/icarus#23]
Hi,
My name is Madhu. I am currently working on a research paper based on 'content popularity prediction and caching in fog nodes'. One of the reference papers has used the Icarus tool for simulation. 

I would like to know the process of 
1. How to generate a dataset for the content popularity prediction using Icarus
2. How to use our own algorithm (deep neural network in my case) to predict the popularity.

Kindly help me with this issue. Thanks a lot in advance.

**Comment by lorenzosaino** [comment]
Hi Madhu,

I am not sure I understand your use case. Could you elaborate more what you'd like to do?

Best regards,
Lorenzo

**Comment by madhucharan** [comment]
Hi,
Let me explain to you a bit clear about our use case. we are writing a research paper on content popularity prediction and fog caching in IoT devices. We came across a research paper comparing 4 different algorithms(LRU etc) existing in Icarus already comparing their approach with the simulation with Icarus software. Our research paper is comparing our approach(here we use a deep neural network for content popularity prediction) with existing algorithms.

For this, we either need to simulate the environment or we need to generate data with some request rate, popularity range, etc which is done by Icarus as simulation. We in general don't know how to create such a dataset.

So my question is- is there any way to save the data generated with the help of Icarus simulation i.e the requests, popularity, and other parameters which are generated through some mathematical distributions, such that we will use our deep learning approach to predict the popular content through the parameters/dataset provided.

**Comment by lorenzosaino** [comment]
Hi Madhu, if I understand correctly you want to run simulations and produce a dataset with the log of all requests that were issued during the simulation that then you want to use to train your neural network. Am I correct?

The answer is yes, but you will need to do some implementation work. When you create a configuration for simulation you can specify what data collectors to use. Here is the list of all data collectors currently implemented: https://github.com/icarus-sim/icarus/blob/master/icarus/execution/collectors.py. You would need to implement a new collector that logs all requests and configure your simulation to use that new collector.

**Comment by madhucharan** [comment]
Yeah, I am asking the data simulation because I observed that icarus is mostly supporting general(custom as well) algorthms but not deep neural networks for content popularity prediction. So I want to extract the simulation and use it for DNN predictions and then compare against the extising algorithms.

would you please let me know implimenting a collector is doable or not?since I might need to learn few more things to do that without many errors. if there is a simple way to do it, could you please guide me implimenting it

**Comment by lorenzosaino** [comment]
It should not be too difficult if you are familiar with Python. You will need to create a class that inherits from `DataCollector` (see https://github.com/icarus-sim/icarus/blob/510aa62d44b3843ddfb31fc67bd97bc7740fa382/icarus/execution/collectors.py#L31-L151) and overrides all methods that you need. Each method is gets called during the experiment execution to notify an event to the data collector. You can see the documentation in the code for what each method does. Also, you may want to read this paper for an overview of Icarus architecture, including data collectors: https://lorenzosaino.github.io/publications/icarus-simutools14.pdf

An simple example implementation of a data collector that's used for testing is here:
https://github.com/icarus-sim/icarus/blob/510aa62d44b3843ddfb31fc67bd97bc7740fa382/icarus/execution/collectors.py#L507-L561

Only thing to be aware of is that this line here (https://github.com/icarus-sim/icarus/blob/510aa62d44b3843ddfb31fc67bd97bc7740fa382/icarus/execution/collectors.py#L507) serves the purpose of assigning a name to your data collector that you can then refer in your configuration when running simulations.

Hope this helps. Best of luck with your research!

**Comment by lorenzosaino** [comment]
I am closing the issue for now. Feel free to reopen it if you still have further issues.
