### ISSUE TITLE
Inquiry regarding the Icarus simulator

### ISSUE THREAD

**Issue by PCIITI** [icarus-sim/icarus#25]
Dear Sir,

Thank you for providing us with such a powerful tool for developing caching strategies in the ICN environment. Sir, as I am new to the Icarus tool, I have some queries, which I have listed below. I understand that you are very busy, but I would like to request that you please resolve my concerns, for which I am grateful.

1. Is it possible to construct NDN Interest and Data packet frameworks, as well as CS, PIT, and FIB data structures, and if so, how? 
2. How to calculate RTT among nodes, is RTT function can be implemented in collector.py file?
3. How to convert a result.pickle file into a result.txt file, as well as how to use the visualise module to draw a graph?

Thanks and Regards 
Pankaj

**Comment by PCIITI** [comment]
Sorry for bothering you again; I have another question. I am attempting to implement a cooperative caching strategy in the Icarus simulator, similar to the SDN controller. Here, I am trying to make one router/caching node (C1) as a centralized, and they share information of cached packets with the other nodes so that other caching nodes cannot store the same data that is already available in C1.

**Comment by lorenzosaino** [comment]
Hi Pankaj, 

Here are the answers to your questions.

> Is it possible to construct NDN Interest and Data packet frameworks, as well as CS, PIT, and FIB data structures, and if so, how?

No. Icarus is a high level simulation specifically targeting caching. You cannot implement and simulate low level protocol aspects such as Interest/Data, FIB, PIT, only caches. You can details of Icarus design and motivation here: https://lorenzosaino.github.io/publications/icarus-simutools14.pdf. You may want to consider lower-level simulators (like ndnSim) if you need lower level abstractions.

> How to calculate RTT among nodes, is RTT function can be implemented in collector.py file?

What do you mean with "RTT function"? Do you mean how to assign RTT values to links?

> How to convert a result.pickle file into a result.txt file, as well as how to use the visualise module to draw a graph?

How do you expect results.txt to be formatted? Human-readable? CSV? Something else? In any case, you can run: 

```
icarus results print <RESULTS_PICKLE_FILE> > <OUTPUT_TEXT_FILE>
```

to print results in a user-friendly format or

```
icarus results print --json <RESULTS_PICKLE_FILE> > <OUTPUT_TEXT_FILE>
```

to print in JSON format. From the JSON file, you can then use tools like `jq` to filter/extract data.

As for visualizing results, there's nothing that would plot your results out of the box. You will need to write some Python code to plot results to use the functions in the visualize package. Here is an example:
https://github.com/icarus-sim/icarus/blob/master/examples/offpath-vs-onpath-caching/plotresults.py 

>  I am attempting to implement a cooperative caching strategy in the Icarus simulator, similar to the SDN controller. Here, I am trying to make one router/caching node (C1) as a centralized, and they share information of cached packets with the other nodes so that other caching nodes cannot store the same data that is already available in C1.

You should be able to do it with Icarus. You can control all request processing flows from within the implementation of a caching strategy. A class implementing a `Strategy` abstract class have access to instances of `NetworkView` and `NetworkController`. Those two instances implement methods that would allow you to do all you need.

Best of luck with your research.

**Comment by PCIITI** [comment]
Thank you very much, sir, for your prompt and valuable response. I noticed that the "LATENCY" function is already available in the collector.py file for RTT calculation.
