### ISSUE TITLE
Support fora assign statements 0.9.x

### ISSUE THREAD

**Issue by TomO700** [icarus-sim/icarus#27]
Hi,

May I check whether you have a limitation on assign statements for version 0.9.7 and 0.9.8 of icarus?
Seems like assigns work only when constant values are assigned.

Thanks

**Comment by lorenzosaino** [comment]
Hello,

I think this is not the Icarus project you may be looking for. The latest Icarus version is 0.8.1 (see https://github.com/icarus-sim/icarus/blob/master/CHANGELOG.md#081).

I am closing this issue for now, feel free to reopen if this is the right project.
