### ISSUE TITLE
Unable to see `No Caching`  Strategy plots in examples

### ISSUE THREAD

**Issue by PechimuthuMithil** [icarus-sim/icarus#37]
In the [plotresults.py](https://github.com/icarus-sim/icarus/blob/master/examples/offpath-vs-onpath-caching/plotresults.py)  code the data for the no-cache strategy is being deleted for the case of cache hit ratio due to which in latency plots we are unable to see "No caching" strategy.

**Comment by lorenzosaino** [comment]
Thanks for reporting it. This is now fixed
