### ISSUE TITLE
Apportionment function produces `TypeError: integer argument expected, got float`

### ISSUE THREAD

**Issue by heliodor** [icarus-sim/icarus#6]
https://github.com/icarus-sim/icarus/blob/master/icarus/util.py#L742

Try for example `apportionment(99, [0.2,0.7,0.1])`

The root cause is that `divmod` returns floats, not ints. You can cast the items in the `ints` list to ints or just cast `to_alloc` to an int.

Code:
```
idx = heapq.nlargest(to_alloc, range(len(remainders)), remainders.__getitem__)
```

Result:
```
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/heapq.py", line 470, in nlargest
    result = _nlargest(n, it)
TypeError: integer argument expected, got float
```

**Comment by lorenzosaino** [comment]
Hi @heliodor, thanks for reporting this issue. It's now fixed.
